
<html><head><meta content="text/html; charset=UTF-8" http-equiv="content-type">
<link rel="stylesheet" type="text/css" href="index.css">
<style>
@media (orientation: landscape) {
  body > div {
    margin-left: auto;
    margin-right: auto;
    max-width: 32em;
  }
}
@media (orientation: portrait) {
  body > div {
    margin-left: 5px;
    margin-right: 5px;
  }
  img.screenshot {
    width: 100%;
  }
}
span.h1 {
  font-size: 2em;
  font-weight: bold;
  display: block;
}
blockquote {
  font-family: Arial;
}
</style>
</head><body>@(include "menu.elm")<div>

<h1>Program Your Google Home:<br>DialogFlow and Google Script</h1>
<em>2020/09/13 &mdash; Mikaël Mayer</em>.<br>
<i>"Ok Google, talk to my </a>.</i>

</body>
</html>